// AUTO-GENERATED by scripts/convert-gallery.mjs — do not edit by hand.
export interface GalleryPhoto {
  src: string;
  width: number;
  height: number;
  alt: string;
}

export const GALLERY_PHOTOS: GalleryPhoto[] = [
  {
    "src": "/gallery/cruz-01.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 1"
  },
  {
    "src": "/gallery/cruz-02.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 2"
  },
  {
    "src": "/gallery/cruz-03.webp",
    "width": 1440,
    "height": 1920,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 3"
  },
  {
    "src": "/gallery/cruz-04.webp",
    "width": 1440,
    "height": 1920,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 4"
  },
  {
    "src": "/gallery/cruz-05.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 5"
  },
  {
    "src": "/gallery/cruz-06.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 6"
  },
  {
    "src": "/gallery/cruz-07.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 7"
  },
  {
    "src": "/gallery/cruz-08.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 8"
  },
  {
    "src": "/gallery/cruz-09.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 9"
  },
  {
    "src": "/gallery/cruz-10.webp",
    "width": 1440,
    "height": 1920,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 10"
  },
  {
    "src": "/gallery/cruz-11.webp",
    "width": 1440,
    "height": 1920,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 11"
  },
  {
    "src": "/gallery/cruz-12.webp",
    "width": 1440,
    "height": 1920,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 12"
  },
  {
    "src": "/gallery/cruz-13.webp",
    "width": 1440,
    "height": 1920,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 13"
  },
  {
    "src": "/gallery/cruz-14.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 14"
  },
  {
    "src": "/gallery/cruz-15.webp",
    "width": 1440,
    "height": 1920,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 15"
  },
  {
    "src": "/gallery/cruz-16.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 16"
  },
  {
    "src": "/gallery/cruz-17.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 17"
  },
  {
    "src": "/gallery/cruz-18.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 18"
  },
  {
    "src": "/gallery/cruz-19.webp",
    "width": 1440,
    "height": 1920,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 19"
  },
  {
    "src": "/gallery/cruz-20.webp",
    "width": 1440,
    "height": 1920,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 20"
  },
  {
    "src": "/gallery/cruz-21.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 21"
  },
  {
    "src": "/gallery/cruz-22.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 22"
  },
  {
    "src": "/gallery/cruz-23.webp",
    "width": 1440,
    "height": 1920,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 23"
  },
  {
    "src": "/gallery/cruz-24.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 24"
  },
  {
    "src": "/gallery/cruz-25.webp",
    "width": 1440,
    "height": 1920,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 25"
  },
  {
    "src": "/gallery/cruz-26.webp",
    "width": 1440,
    "height": 1920,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 26"
  },
  {
    "src": "/gallery/cruz-27.webp",
    "width": 1440,
    "height": 1920,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 27"
  },
  {
    "src": "/gallery/cruz-28.webp",
    "width": 1440,
    "height": 1920,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 28"
  },
  {
    "src": "/gallery/cruz-29.webp",
    "width": 1440,
    "height": 1920,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 29"
  },
  {
    "src": "/gallery/cruz-30.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 30"
  },
  {
    "src": "/gallery/cruz-31.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 31"
  },
  {
    "src": "/gallery/cruz-32.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 32"
  },
  {
    "src": "/gallery/cruz-33.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 33"
  },
  {
    "src": "/gallery/cruz-34.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 34"
  },
  {
    "src": "/gallery/cruz-35.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 35"
  },
  {
    "src": "/gallery/cruz-36.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 36"
  },
  {
    "src": "/gallery/cruz-37.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 37"
  },
  {
    "src": "/gallery/cruz-38.webp",
    "width": 1440,
    "height": 1920,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 38"
  },
  {
    "src": "/gallery/cruz-39.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 39"
  },
  {
    "src": "/gallery/cruz-40.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 40"
  },
  {
    "src": "/gallery/cruz-41.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 41"
  },
  {
    "src": "/gallery/cruz-42.webp",
    "width": 1920,
    "height": 1440,
    "alt": "Custom carpentry and millwork by Cruz Carpentry — project 42"
  }
];
