// One-off: convert source JPGs to web-optimized WebP in public/gallery/ and
// emit the gallery manifest (src/components/gallery/photos.ts).
//
// Usage: node scripts/convert-gallery.mjs <source-dir>
// Source assets live outside the repo; re-run only when the photo set changes.
import { readdir, mkdir, writeFile, rm } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const MAX_EDGE = 1920;
const QUALITY = 80;
const sourceDir = process.argv[2];

if (!sourceDir) {
  console.error("Usage: node scripts/convert-gallery.mjs <source-dir>");
  process.exit(1);
}

const projectRoot = path.resolve(import.meta.dirname, "..");
const outDir = path.join(projectRoot, "public", "gallery");
const manifestPath = path.join(
  projectRoot,
  "src",
  "components",
  "gallery",
  "photos.ts",
);

// Start from a clean output dir so a shrinking source set can't orphan stale
// cruz-NN.webp files in the build.
await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

// Deterministic, but ordered by lexicographic source filename — `cruz-01` is
// not stable if the source set is renamed or has files inserted. Re-running
// rewrites all names + the manifest from scratch.
const sources = (await readdir(sourceDir))
  .filter((f) => /\.(jpe?g|png)$/i.test(f))
  .sort();

const photos = [];
let index = 0;

for (const file of sources) {
  index += 1;
  const name = `cruz-${String(index).padStart(2, "0")}.webp`;
  const info = await sharp(path.join(sourceDir, file))
    .rotate() // honor EXIF orientation
    .resize({ width: MAX_EDGE, height: MAX_EDGE, fit: "inside", withoutEnlargement: true })
    .webp({ quality: QUALITY })
    .toFile(path.join(outDir, name));

  photos.push({ src: `/gallery/${name}`, width: info.width, height: info.height });
  console.log(`${file} -> ${name} (${info.width}x${info.height}, ${Math.round(info.size / 1024)}KB)`);
}

const body = `// AUTO-GENERATED by scripts/convert-gallery.mjs — do not edit by hand.
export interface GalleryPhoto {
  src: string;
  width: number;
  height: number;
  alt: string;
}

export const GALLERY_PHOTOS: GalleryPhoto[] = ${JSON.stringify(
  photos.map((p, i) => ({
    ...p,
    alt: `Custom carpentry and millwork by Cruz Carpentry — project ${i + 1}`,
  })),
  null,
  2,
)};
`;

await writeFile(manifestPath, body);
console.log(`\nWrote ${photos.length} photos to ${outDir}`);
console.log(`Wrote manifest ${manifestPath}`);
